apiVersion: v1
kind: ConfigMap
metadata:
  name: itch150-nginx-conf
data:
  nginx.conf: |
    error_log /dev/stderr;
    pid /dev/null;
    events {
      worker_connections 64;
    }
    http {
      log_format main '[$time_local] code=$status bytes_sent=$bytes_sent req="$request"';
      proxy_headers_hash_bucket_size 128;
      proxy_buffering off;
      types {
          application/javascript     js;
          text/css                   css;
          text/html                  html;
      }
      default_type  application/octet-stream;
      server {
        access_log /dev/stderr main;
        location /umbraluna/ {
          root /opt;
        }
        location ~ /umbraluna/.*wasm\.gz$ {
            root /opt;
            add_header Content-Encoding gzip;
            default_type  application/wasm;
        }
        location ~ /umbraluna/.*\.gz$ {
            root /opt;
            add_header Content-Encoding gzip;
        }
      }
    }